# Generated by Django 2.2.17 on 2021-01-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanuel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provaaluno',
            old_name='nome_do_aluno',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='provaaluno',
            old_name='nome_materia',
            new_name='prova',
        ),
        migrations.AlterField(
            model_name='gab',
            name='nome_materia',
            field=models.CharField(max_length=55, unique=True, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_1_1',
            field=models.CharField(max_length=100, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_1_2',
            field=models.CharField(max_length=100, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_1_3',
            field=models.CharField(max_length=100, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_2_1',
            field=models.CharField(max_length=100, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_2_2',
            field=models.CharField(max_length=100, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_2_3',
            field=models.CharField(max_length=100, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_3_1',
            field=models.CharField(max_length=100, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_3_2',
            field=models.CharField(max_length=100, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_3_3',
            field=models.CharField(max_length=100, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_4_1',
            field=models.CharField(max_length=100, verbose_name='a'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_4_2',
            field=models.CharField(max_length=100, verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='opcao_4_3',
            field=models.CharField(max_length=100, verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='questao_1',
            field=models.CharField(max_length=100, verbose_name='Questão 1'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='questao_2',
            field=models.CharField(max_length=100, verbose_name='Questão 2'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='questao_3',
            field=models.CharField(max_length=100, verbose_name='Questão 3'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='questao_4',
            field=models.CharField(max_length=100, verbose_name='Questão 4'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='resposta_da_questao_1',
            field=models.CharField(max_length=1, verbose_name='resposta'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='resposta_da_questao_2',
            field=models.CharField(max_length=1, verbose_name='resposta'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='resposta_da_questao_3',
            field=models.CharField(max_length=1, verbose_name='resposta'),
        ),
        migrations.AlterField(
            model_name='gab',
            name='resposta_da_questao_4',
            field=models.CharField(max_length=1, verbose_name='reaposta'),
        ),
        migrations.AlterField(
            model_name='provaaluno',
            name='resposta_do_aluno_questao_1',
            field=models.CharField(max_length=1, verbose_name='Resposta 1ª'),
        ),
        migrations.AlterField(
            model_name='provaaluno',
            name='resposta_do_aluno_questao_2',
            field=models.CharField(max_length=1, verbose_name='Resposta 2ª'),
        ),
        migrations.AlterField(
            model_name='provaaluno',
            name='resposta_do_aluno_questao_3',
            field=models.CharField(max_length=1, verbose_name='Resposta 3ª'),
        ),
        migrations.AlterField(
            model_name='provaaluno',
            name='resposta_do_aluno_questao_4',
            field=models.CharField(max_length=1, verbose_name='Resposta 4ª'),
        ),
    ]
