# Generated by Django 2.2.17 on 2021-02-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emanuel', '0003_auto_20210131_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gabarito',
            old_name='nome_materia',
            new_name='gabarito',
        ),
        migrations.RenameField(
            model_name='prova',
            old_name='provas',
            new_name='gabarito',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='nome_da_materia',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='nota_da_prova_1',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='nota_da_prova_2',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='nota_da_prova_3',
        ),
        migrations.RemoveField(
            model_name='situacao',
            name='nota_da_prova_4',
        ),
        migrations.AddField(
            model_name='situacao',
            name='curso',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='aluno',
            field=models.ForeignKey(max_length=55, on_delete=django.db.models.deletion.CASCADE, related_name='situacoes', to='emanuel.Aluno'),
        ),
    ]
