# Generated by Django 2.2.17 on 2021-02-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emanuel', '0005_auto_20210201_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ('id',), 'verbose_name': 'aluno', 'verbose_name_plural': 'alunos'},
        ),
        migrations.AlterModelOptions(
            name='gabarito',
            options={'ordering': ('id',), 'verbose_name': 'gabarito', 'verbose_name_plural': 'gabaritos'},
        ),
        migrations.AlterModelOptions(
            name='prova',
            options={'ordering': ('aluno',), 'verbose_name': 'prova', 'verbose_name_plural': 'provas'},
        ),
        migrations.AlterModelOptions(
            name='situacao',
            options={'ordering': ('id',), 'verbose_name': 'situacao', 'verbose_name_plural': 'situacoes'},
        ),
    ]
